export const map: string;
export const restaurantPin: string;
export const info: string;
export const meta: string;
export const openingHoursContainer: string;
export const openingHours: string;
export const day: string;
export const hours: string;
export const mapLabel: string;
